# Generated by Django 5.0 on 2024-12-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_unique_budget_budget_unique_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
