# Generated by Django 5.0 on 2023-12-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
