# Generated by Django 5.0 on 2024-06-01 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.RemoveField(
            model_name='plaiditem',
            name='id',
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='max_lookback_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plaiditem',
            name='item_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mask', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('iso_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_lookback_days', models.IntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaidapp.plaiditem')),
            ],
            options={
                'verbose_name': 'Plaid Account',
                'verbose_name_plural': 'Plaid Accounts',
            },
        ),
        migrations.CreateModel(
            name='PlaidItemSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced', models.DateTimeField()),
                ('last_failed', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaidapp.plaiditem')),
            ],
            options={
                'verbose_name': 'Plaid Item Sync',
                'verbose_name_plural': 'Plaid Item Syncs',
            },
        ),
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pending', models.BooleanField()),
                ('status', models.CharField(choices=[('REMOVED', 'Removed'), ('ADDED', 'Added'), ('MODIFIED', 'Modified')], default='ADDED', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaidapp.plaidaccount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaidapp.plaiditem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plaidapp.location')),
            ],
        ),
    ]
