# Generated by Django 5.0 on 2023-12-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
