# Generated by Django 5.0 on 2024-06-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapp', '0001_initial'),
        ('transaction', '0004_alter_transaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plaidapp.plaidtransaction'),
        ),
    ]
