# Generated by Django 5.0 on 2024-06-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='reccuring_frequency',
            new_name='recurring_frequency',
        ),
    ]
